### ISSUE TITLE
[Client bug]: NextPageRequest is inside AdditionalData instead of the designated field in C#  beta SDK.

### ISSUE THREAD

**Issue by Danialmz96** [microsoftgraph/msgraph-beta-sdk-dotnet#291]
The NextPageRequest property inside some collection pages is null and appears as an entry inside AdditionalData using the C# beta SDK.

Reproduce:
var groupsPage = await confidentialGraphClient.Groups.Request().GetAsync();
if(groupsPage.NextPageRequest != null)
{
//will skip this scope
}

if(groupsPage.AdditionalData.ContainsKey("@odata.nextLink"))
{
//will enter this scope
}

SDK version: 4.1.0-preview and 4.0.1-preview

The NextPageRequest property is expected to hold the next page URL.

Aside from the given example, I am not sure which collection pages behave this way and if I find any I'll add them here.
 
[AB#9204](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9204)

**Comment by andrueastman** [comment]
@Danialmz96 Can you confirm that the behavior is consistent for both version 4.0.1-preview and 4.1.0-preview?
I believe we had an issue with initialization of `NextPageRequest` but that was resolved in 4.1.0-preview via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/275

**Comment by Danialmz96** [comment]
@andrueastman I just rechecked using 4.1.0-preview and I can confirm it is still happening using the example if posted.

**Comment by andrueastman** [comment]
@Danialmz96 Thanks again for your patience and trying the new preview. The issue should now be resolved via https://www.nuget.org/packages/Microsoft.Graph.Beta/4.2.0-preview
