### ISSUE TITLE
Missing method for permanently delete item from directory object

### ISSUE THREAD

**Issue by Edgarus79** [microsoftgraph/msgraph-beta-sdk-dotnet#792]
According to the documentation of Microsoft Graph REST API Beta, there is a method to permanently delete applications users and groups:
DELETE https://graph.microsoft.com/beta/directory/deleteditems/{id}
However it's missing in latest Microsoft.Graph.Beta (5.63.0-preview)
![image](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/assets/35922672/fabce32a-907c-4561-b6ab-a311a7c8a612)
Can someone please confirm that method is missing or maybe it has been moved.

**Comment by andrueastman** [comment]
Thanks for raising this @Edgarus79 

This looks to be a metadata issue affecting the beta metadata and should be resolved via https://github.com/microsoftgraph/msgraph-metadata/issues/566

**Comment by Friendry606** [comment]
Hello, @andrueastman  any update on this? 

The issue seems to still appear in the latest version of the library

**Comment by andrueastman** [comment]
Closing this one for now as it is possible to call in the latest version at https://www.nuget.org/packages/Microsoft.Graph.Beta/5.78.0-preview

```cs
await graphClient.Directory.DeletedItems["item-id"].DeleteAsync();
```
